name: Bree API

on:
  push:
    branches: [ "master" ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm audit --audit-level=high --omit=dev
        continue-on-error: true
      - run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd ~/repositories/nwed-nyin-api
            git pull origin main
            npm i
            npm run build
            npx prisma migrate dev
            pm2 restart nwed-nyin-api
