name: Bree API

on:
  push:
    branches: [ "master" ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd ~/repositories/nwed-nyin-api
            git pull origin main
            npm i
            npm run build
            npx prisma migrate dev
            pm2 restart nwed-nyin-api
